# Site settings
baseurl = "https://www.vektorcr.tk/"
languageCode = "en-us"
title = "Rancho 77"

googleAnalytics = "" #put your google-analytics ID here

[params]
  [params.header]
    title = "Rancho 77"
    description = 'Breve Descripción de rancho 77 (Se debe escoger la imagen que aparecera acá)'
    image = "images/logo.svg"

  [[params.navigation]]
    name = "Quienes Somos"
    href = "#intro"

  [[params.navigation]]
    name = "Servicios"
    href = "#first"

  [[params.navigation]]
    name = "Restaurante y Cafeteria"
    href = "#second"

  [[params.navigation]]
    name = "Co-Breting"
    href = "#cta"  

[[params.navigation]]
    name = "Eventos"
    href = "#cta"  

  [params.intro]
    title = "Quienes Somos en Rancho 77"
    description = "Breve descripción rancho 77 (Se debe cambiar la imagen de la derecha)"
    image = "images/pic01.jpg"

  [[params.section]]
    id = "first"
    title = "Nuestros Servicios"
    description = "Breve descripción (general) de los servicios"
    
    # the picture is storead at static/images/
    [params.section.features]
      enable = true
      [[params.section.feature]]
        title = "Restaurante y cafeteria"
        description = "Sobre los servicios del restaurante"
        icon = "fa-cutlery"

      [[params.section.feature]]
        title = "Co-Breting"
        description = "Sobre los servicios del Co-Breting"
        icon = "fa-laptop"

      [[params.section.feature]]
        title = "Eventos"
        description = "Sobre los eventos"
        icon = "fa-calendar"
    [params.section.footer]
      enable = false
      [[params.section.footer.action]]
        buttontext = "Learn More"
        buttonUrl = "generic.html"

  [[params.section]]
    id = "second"
    title = "Restaurante y Cafeteria"
    description = "Breve descripción del restaurante y la cafeteria"

    [params.section.statistics]
      enable = true
      [[params.section.statistic]]
        icon = "fa-lemon-o"
        value = "7-10"
        text = "Desayunos"
      [[params.section.statistic]]
        icon = "fa-cutlery"
        value = "11-3"
        text = "Almuerzos"
      [[params.section.statistic]]
        icon = "fa-coffee"
        value = "2-5"
        text = "Cafe de la tarde"
      [[params.section.statistic]]
        icon = "fa-beer"
        value = "2-5"
        text = "Jugos"
      [[params.section.statistic]]
        icon = "fa-glass"
        value = "6-10"
        text = "Bebidas"

    [params.section.content]
      enable = true
      text = "Descripcion de servicios de comida (Pueden ser varias columnas) ppppp slkasaks sklakslaks kslakslks skalsklaskla skallkslaks skalsklsklask klsaklsklas skalksla s kslakslaks klkslklklfkopf"

    [params.section.footer]
      enable = false
      [[params.section.footer.action]]
        buttontext = "Learn More"
        buttonUrl = "generic.html"


  [[params.section]]
    id = "cta"
    title = "Co-Breting"
    description = "Breve descripcion del co breting"
    [params.section.footer]
      enable = false
      [[params.section.footer.action]]
        buttontext = "Learn More"
        buttonUrl = "generic.html"

  [params.footer]
    enable = true
    title = "Titulo"
    description = "Pequeña Descripción que se quiere recalcar (se debe escoger las direcciones de las redes sociales)"

    second_title = "Contactenos"
    address = "400 Oeste de Panasonic. San Rafael, Alajuela. CR"
    phone = "+506-8884-1598"
    email = "centroderecreosp@gmail.com "

    #[[params.footer.action]]
    #  href = "generic.html"
    #  buttontext = "Learn More"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "#"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "https://www.facebook.com/ranchosietesiete-102598337890997/"

      [[params.footer.social]]
        title = "Instagramm"
        icon = "fa-instagram"
        link = "#"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "#"

    # copyright
    [params.footer.copyright]
      enable = false
      text = "© Untitled, Design: [HTML5UP](//html5up.net)"